Add text about text directionality to the note in rdf:HTML.
w3c/rdf-concepts pull request #107
Opened 2024-10-22 20:39 UTC by gkellogg

Fixes #102.

2024-10-22 20:43 UTC, domel requested changes
... - > …(in the lang attr there is one sign with three dots and in dir there are three separate dots). Let's unify it.

2024-10-22 20:43 UTC, afs approved these changes

2024-10-22 20:57 UTC, gkellogg commented on spec/index.html
> +      text directionality annotation (<code>dir="..."</code>), or
```suggestion
      text directionality annotation (<code>dir="…"</code>), or
```

2024-10-22 21:38 UTC, domel approved these changes

2024-10-23 03:39 UTC, iherman approved these changes
Approving with the suggested change by @domel

2024-10-23 05:57 UTC, hartig approved these changes

2024-10-23 14:31 UTC, merged