Improve list types (`ol` vs `ul`) and content (grammar, punctuation, …
w3c/rdf-concepts pull request #108
Opened 2024-10-24 20:04 UTC by TallTed

…etc.)

2024-10-24 20:55 UTC, gkellogg approved these changes

2024-10-25 06:11 UTC, hartig requested changes

2024-10-25 06:11 UTC, hartig commented on spec/index.html
>        graphs, such that:</p>
```suggestion
      graphs, such that all of the following properties hold:</p>
```

2024-10-25 06:11 UTC, hartig commented on spec/index.html
>        <var>D1</var> and those in <var>D2</var> such that:</p>
```suggestion
      <var>D1</var> and those in <var>D2</var> such that all of the following properties hold:</p>
```

2024-10-28 17:03 UTC, hartig approved these changes

2024-10-29 19:22 UTC, merged