Remove 'recognized datatype iri' in favor of RDF Semantics definition and use
w3c/rdf-concepts pull request #124
Opened 2024-12-21 15:01 UTC by afs

Important: 

RDF-Semantics has never referenced RDF-Concepts for "recognized datatypes".
It has its own definition [dfn-recognized](https://www.w3.org/TR/rdf12-semantics/#dfn-recognize).

There are two places that cover accepting literals. One is for literals with unknown dataypes, [section DatatypeIRIs](https://www.w3.org/TR/rdf12-concepts/#datatype-iris) and one is for known-to-be [ill-typed literals](https://www.w3.org/TR/rdf12-concepts/#section-Graph-Literal). In RDF 1.1 they were MUST and SHOULD. In this PR, they are both SHOULD. RDF Semantics provides further restrictions for D-entailment and it's definition of "_recognized_" datatype IRIs.

This closes #122.
This closes #60.

2024-12-21 15:44 UTC, afs commented
cc @rdfguy

2024-12-27 23:40 UTC, gkellogg approved these changes

2025-01-03 16:17 UTC, TallTed requested changes
Small, editorial, mostly punctuation

2025-01-03 16:17 UTC, TallTed commented on spec/index.html
> +      semantic error.<p>
```suggestion
    <p>RDF processors are not required to handle all datatypes.
      Any literal typed with a datatype IRI not handled by an RDF processor
      is treated just like an unknown IRI, i.e., as referring to an unknown thing.
      Applications MAY give a warning message if they are unable to determine the
      referent of an IRI used in a typed literal. RDF processors SHOULD NOT
      reject a literal with an unknown IRI as either a syntactic or
      semantic error.<p>
```

2025-01-03 16:17 UTC, TallTed commented on spec/index.html
> +      were defined RDF Concepts, overlapping with
```suggestion
      In RDF 1.1, <em><span id="dfn-recognized-datatype-iris">Recognized datatype IRIs</span></em>
      were defined in RDF Concepts, overlapping with 
```

2025-01-03 16:17 UTC, TallTed commented on spec/index.html
> +      were defined RDF Concepts, overlapping with
or possibly
```suggestion
      In RDF 1.1, <em><span id="dfn-recognized-datatype-iris">Recognized datatype IRIs</span></em>
      were defined by RDF Concepts, overlapping with 
```

2025-01-03 16:17 UTC, TallTed commented on spec/index.html
>              <a>lexical form</a>.</li>
```suggestion
            <a>lexical form</a>;</li>
```

2025-01-07 10:27 UTC, doerthe commented on spec/index.html
> +        handled by an RDF processor then the literal value is
I think the RDF processor needs further explanation. Is it introduced somewhere? Could we add a link?

2025-01-08 18:09 UTC, hartig requested changes

2025-01-08 18:09 UTC, hartig commented on spec/index.html
> +      semantic error.<p>
There is a slight inconsistency in this paragraph. According to the first sentence, the things that RDF processors may handle are the datatypes. Yet, according to the second sentence, it is datatype IRIs that RDF processors may (or may not) handle. We should settle on one or the other (datatypes or datatype IRIs).

My preference would be for datatypes instead of datatype IRIs. In this case, the second sentence here should be change to: "Any literal typed with a datatype IRI that denotes a datatype that is not handled by ..."

Then, the new line 746 (see above) should be changed accordingly: "If the <a>datatype</a> denoted by the literal's <a>datatype IRI</a> is handled by ..."

2025-01-09 12:00 UTC, pchampin commented on spec/index.html
> +    <p>Datatypes are identified by <a>IRIs</a> and the <a>referent</a>
> To be consistent with the terminology in the definition of [datatype](https://pr-preview.s3.amazonaws.com/w3c/rdf-concepts/pull/124.html#dfn-datatype) :

actually, the term "identified" is the correct one, see 1st paragraph of https://www.w3.org/TR/rdf12-semantics/#datatypes . So the definition of datatypes in rdf-concepts should probably be fixed...

2025-01-09 12:00 UTC, pchampin commented on spec/index.html
> +            of datatype, then the literal value is the result of applying
I think that replacing "datatype" with "the datatype" should be enough and less verbose.

If we go the verbose way, note that the correct word should be "identified" rather than "denote" (see my other comment on this below).

2025-01-09 12:00 UTC, pchampin commented on spec/index.html
> +      <li>If the literal's <a>datatype IRI</a> is handled by an RDF processor,
I find the wording "an RDF processor" strange, all the more that it is repeated below...
Implicitly, we are referring to the *same* processor all along this paragraph, so replacing this (and the other occurrence) with "the RDF processor" would seem better.

Also, the term "RDF processor" is currently only used twice in RDF-Concepts (a little more after this PR), and only in relation with datatypes. Anywhere else in the spec, we talk about Applications and Implementations. Wouldn't it be better to stick to one of these?
```suggestion
      <li>If the literal's <a>datatype IRI</a> is handled by the implementation,
```

2025-01-09 12:00 UTC, pchampin commented on spec/index.html
> +        handled by an RDF processor then the literal value is
```suggestion
        handled by the implementation, then the literal value is
```
(see my comment above about "an RDF processor")

2025-01-09 12:48 UTC, afs commented on spec/index.html
> +      <li>If the literal's <a>datatype IRI</a> is handled by an RDF processor,
I'd be happy to remove "RDF Processor" from RDF Concepts  - it's informal but looks formal; it is only for datatypes.

"RDF processor" is used in RDF Semantics more (5 times) so it looks like another thing that has come over from there.

2025-01-09 13:08 UTC, afs commented on spec/index.html
> +    <p>Datatypes are identified by <a>IRIs</a> and the <a>referent</a>
RDF Semantics then says "denoted".

>Datatypes are [identified](https://www.w3.org/TR/rdf12-semantics/#dfn-identify) by IRIs. Interpretations will vary according to which IRIs are recognized as denoting datatypes.

_I think_ the point is "identified" is about the usage made in the `^^` position. If so, "identified" would be better in line 1294.

I have changed the definition "and is denoted by" to and is identified by" for consistency.

If there are further thoughts, can we deal with these in a separate issue/pr? This is orthogonal to removing "recognized datatype IRI" from RDF Concepts.

2025-01-09 13:23 UTC, afs commented on spec/index.html
> +      semantic error.<p>
OK - I will make the change here and L746.

As for more general "datatype IRI" -> "datatype", please could we have a separate PR? By bundling changes into one PR, it becomes increasingly harder to ensure, and review, that it is done outside the areas touched by the initial PR.

2025-01-09 13:32 UTC, afs commented on spec/index.html
>              <a>lexical form</a>.</li>
For reasons unknown, the most (not all) bulleted lists in the doc have `'` on each list item. It would be better to deal with this separately because this PR is growing in scope already and I think keeping it as focused as possible will help get it accepted.

2025-01-09 13:34 UTC, afs commented on spec/index.html
> +            of datatype, then the literal value is the result of applying
> I think that replacing "datatype" with "the datatype" should be enough and less verbose.

Agreed.

2025-01-09 13:37 UTC, afs commented on spec/index.html
> +      lexical form to a value.</p>
Removing the second part looks good. This isn't the definition of "datatype".

2025-01-09 13:37 UTC, hartig commented on spec/index.html
> +    <p>Datatypes are identified by <a>IRIs</a> and the <a>referent</a>
Yes @afs , based on @pchampin's comment I now also agree the line 1294 should use "identified", exactly as you did in this PR. So, the only thing that remains to be done for line 1294 in this PR is to apply @TallTed's [suggestion of adding a comma](https://github.com/w3c/rdf-concepts/pull/124#discussion_r1901930143).

2025-01-09 13:38 UTC, afs commented on spec/index.html
> +        handled by an RDF processor then the literal value is
I've pushed changes that include changing "RDF processor" to "RDF implenentation".

2025-01-09 14:09 UTC, afs commented on spec/index.html
> +    <p>Datatypes are identified by <a>IRIs</a> and the <a>referent</a>
The subsequent text has been removed as per [your suggestion](https://github.com/w3c/rdf-concepts/pull/124#discussion_r1907584379).

2025-01-09 14:42 UTC, hartig approved these changes

2025-01-09 17:55 UTC, TallTed commented on spec/index.html
>              <a>lexical form</a>.</li>
https://github.com/w3c/rdf-concepts/issues/127

2025-01-09 17:59 UTC, merged