Described IRIs as "fully resolved" rather than "absolute".
w3c/rdf-concepts pull request #58
Opened 2023-08-18 21:14 UTC by gkellogg

For #15.

2023-08-18 21:15 UTC, gkellogg commented
@afs, I think this addresses your concern about the mis-use of "absolute IRI", at least within this document. If the general direction seems reasonable, I can replicate to other specifications.

2023-08-18 21:34 UTC, TallTed requested changes
a yew-are-eye, a yew-are-ell, an eye-are-eye... :-)

2023-08-18 21:34 UTC, TallTed commented on spec/index.html
> +        Every URI and URL is an IRI, but not every IRI is an URI.
```suggestion
        Every URI and URL is an IRI, but not every IRI is a URI.
```

2023-08-19 08:22 UTC, afs commented on spec/index.html
> +      (This is done in the abstract syntax, so the IRIs are fully resolved
```suggestion
      (This is done in the abstract syntax, so the IRIs are resolved
```
I don't think there is a "partially resolved".

2023-08-19 08:28 UTC, afs commented
> @afs, I think this addresses your concern about the mis-use of "absolute IRI", at least within this document. If the general direction seems reasonable, I can replicate to other specifications.

I can't think of a better name at the moment. For other docs, just "IRI" is reasonable. The syntax parsing step will cover the need to make complete. We can overload text about details and harm readability by always putting in our local terminology.

Going back to 3986/3987: I can't find terminology for:
```
URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]
```
with 
```
hier-part   = "//" authority path-abempty
```
but none of the other `hier-part` alternatives.

2023-08-19 08:30 UTC, afs commented on spec/index.html
> +        An IRI reference refers to either a fully resolved <a>IRI</a> or <a>relative IRI reference</a>,
```suggestion
        An IRI reference refers to either a resolved <a>IRI</a> or <a>relative IRI reference</a>,
```

2023-08-19 08:30 UTC, afs commented on spec/index.html
> +          <td><a data-cite="xmlschema11-2#anyURI"><code>xsd:anyURI</code></a></td><td>Fully resolved or relative URI and IRI references</td></tr>
```suggestion
          <td><a data-cite="xmlschema11-2#anyURI"><code>xsd:anyURI</code></a></td><td>Resolved or relative URI and IRI references</td></tr>
```

2023-08-19 08:30 UTC, afs commented on spec/index.html
> +      and clarifies that, in the abstract syntax, IRIs are fully resolved,
```suggestion
      and clarifies that, in the abstract syntax, IRIs are resolved,
```

2023-08-20 19:35 UTC, gkellogg commented on spec/index.html
> +    <p>IRIs in the RDF abstract syntax MUST be <a data-cite="RFC3986#section-5">fully resolved</a>
```suggestion
    <p>IRIs in the RDF abstract syntax MUST be <a data-cite="RFC3986#section-5">resolved</a>
```

2023-08-21 08:53 UTC, hartig approved these changes

2023-08-21 21:20 UTC, afs approved these changes

2023-08-31 19:55 UTC, merged